language: cpp
dist: xenial
sudo: required

git:
  depth: false

env:
  - PATH=/usr/local/bin:${PATH}

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

  include:
    - os: linux
      compiler: clang

    - os: linux
      compiler: gcc

#    - os: osx
#      osx_image: xcode10.1

    - os: windows
      env: PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin:$PATH"
      install:
        - choco install -y cmake
      script:
        - mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
        - cmake ..
        - MSbuild.exe Etterna.sln -t:Etterna /p:Configuration=Release



addons:
  homebrew:
    packages:
      - openssl
      - cmake
    update: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - nasm
      - libudev-dev
      - gcc-5
      - g++-5
      - libmad0-dev
      - libgtk2.0-dev
      - binutils-dev
      - libasound-dev
      - libpulse-dev
      - libjack-dev
      - libc6-dev
      - libogg-dev
      - libvorbis-dev
      - libxtst-dev
      - libxrandr-dev
      - libglew-dev
      - libuv-dev
      - clang-format-5.0
    update: true

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ci_scripts/build.sh; fi

script:
  - clang --version
  - gcc --version
  - cmake --version
  - mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
  - cmake ..
  - make