version: 0.60.0.{build}.{branch}
pull_requests:
  do_not_increment_build_number: true

image:
  - Visual Studio 2017
configuration:
  - Release
platform:
  - x64
environment:
  matrix:
  - arch: Win64
  - arch: Win32

clone_folder: C:\etterna

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

artifacts:
- path: Etterna *.exe
  
install:
- cmd: choco install nsis.portable

init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: git submodule update --init --recursive
- cmd: >-
    
    mkdir build && cd build

    "C:\Program Files (x86)\cmake\bin\cmake" .. -G %generator%

    del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build:
  project: C:\etterna\build\Etterna.sln
  verbosity: normal
  parallel: true

after_build:
- cmd: >-
    
    "C:\Program Files (x86)\NSIS\makensis.exe" "C:\etterna\stepmania.nsi"

- cmd: >-
    rename "C:\etterna\Etterna *.exe" "Etterna *-%appveyor_build_version%.exe"

notifications:
- provider: Email
  to:
  - etternadevs@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true


for:

# override settings for `master` branch
-
  branches:
    only:
      - master

  image:
    - Visual Studio 2013
    - Visual Studio 2015
    - Visual Studio 2017
  configuration:
    - Release
    - RelWithDebInfo
